import '../css/app.css';
import './bootstrap';
import { initAuthModule } from './modules/auth';
import { initLayoutModule } from './modules/layout';
import { initProfileModule } from './modules/profile';
import { initDocsModule } from './modules/docs';
import { initSecurityModule } from './modules/security';
import { initAuditModule } from './modules/audit';
import { initAdministrationModule } from './modules/administration';
import { initDepartmentsModule } from './modules/departments';
import { initHolidaysModule } from './modules/holidays';
import { initShiftsModule } from './modules/shifts';
import { initEmployeesModule } from './modules/employees';
import { initTrainingModule } from './modules/training';
import { initMedicalModule } from './modules/medical';
import { initDocumentsModule } from './modules/documents';
import { initLookupsModule } from './modules/lookups';
import { initSchedulesModule } from './modules/schedules';
import { initDashboardModule } from './modules/dashboard';
import { initApiDocsModule } from './modules/api-docs';
import { initNotificationsModule, initTopbarNotifications } from './modules/notifications';
import { initSearchMega } from './modules/search';

initLayoutModule();
initTopbarNotifications();
initSearchMega();
initProfileModule();
initAuthModule();
initDocsModule();
initSecurityModule();
initAuditModule();
initAdministrationModule();
initDepartmentsModule();
initHolidaysModule();
initShiftsModule();
initEmployeesModule();
initTrainingModule();
initMedicalModule();
initDocumentsModule();
initLookupsModule();
initSchedulesModule();
initDashboardModule();
initApiDocsModule();
initNotificationsModule();
